-- TankMark v0.23
-- File: TankMark_Defaults.lua
-- [v0.23] Default Mob Database - Curated baseline priorities for top-tier content

-- DEFAULT MOB DATABASE
-- This database serves as a fallback and starting point for new users.
-- User customizations in TankMarkDB always take priority.
-- [v0.23] Format: [zone][mobName] = {prio=X, marks={Y,Z,...}, type="TYPE", class=nil}

TankMarkDefaults = {}

-- MOLTEN CORE
TankMarkDefaults["Molten Core"] = {
    ["Lucifron"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Magmadar"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Gehennas"] = {prio=1, marks={8}, type="KILL", class=nil},
    ["Garr"] = {prio=9, marks={0}, type="KILL", class=nil},
    ["Shazzrah"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Baron Geddon"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Sulfuron Harbinger"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Golemagg the Incinerator"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Majordomo Executus"] = {prio=9, marks={0}, type="KILL", class=nil},
    ["Ragnaros"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Flamewaker Healer"] = {prio=1, marks={4}, type="KILL", class=nil},
    ["Flamewaker Elite"] = {prio=1, marks={1}, type="KILL", class=nil},
    ["Flamewaker Priest"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Flamewaker Protector"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Core Hound"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Lava Surger"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Firesworn"] = {prio=1, marks={8}, type="KILL", class=nil},
    ["Ancient Core Hound"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Lava Spawn"] = {prio=3, marks={8}, type="KILL", class=nil},
    ["Lava Elemental"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Firelord"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Flameguard"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Lava Reaver"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Lava Annihilator"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Molten Destroyer"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Molten Giant"] = {prio=4, marks={8}, type="KILL", class=nil},
    ["Core Rager"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Firewalker"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Son of Flame"] = {prio=9, marks={0}, type="KILL", class=nil},
    ["Flame Imp"] = {prio=9, marks={0}, type="KILL", class=nil},
    ["Small Incendic Egg"] = {prio=2, marks={8}, type="KILL", class=nil},
    ["Large Incendic Egg"] = {prio=1, marks={8}, type="KILL", class=nil},
    ["Incindis"] = {prio=6, marks={8}, type="KILL", class=nil},
    ["Spawn of Incindis"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Basalthar"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Smoldaris"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Shadowforge Guardian"] = {prio=4, marks={8}, type="KILL", class=nil},
    ["Shadowforge Blazeweaver"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Shadowforge Hierophant"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Sorcerer-Thane Thaurissan"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Image of Sorcerer-Thane Thaurissan"] = {prio=9, marks={0}, type="KILL", class=nil},
}

-- ONYXIAS LAIR
TankMarkDefaults["Onyxias Lair"] = {
    ["Onyxia"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Onyxian Whelp"] = {prio=9, marks={0}, type="KILL", class=nil},
    ["Onyxian Warder"] = {prio=5, marks={8}, type="KILL", class=nil},
}

-- ZUL'GURUB
TankMarkDefaults["Zul'Gurub"] = {
    ["High Priestess Jeklik"] = {prio=1, marks={8}, type="KILL", class=nil},
    ["High Priest Venoxis"] = {prio=1, marks={8}, type="KILL", class=nil},
    ["High Priestess Marli"] = {prio=4, marks={8}, type="KILL", class=nil},
    ["Bloodlord Mandokir"] = {prio=4, marks={8}, type="KILL", class=nil},
    ["High Priest Thekal"] = {prio=1, marks={4}, type="KILL", class=nil},
    ["High Priestess Arlokk"] = {prio=1, marks={8}, type="KILL", class=nil},
    ["Hakkar"] = {prio=1, marks={8}, type="KILL", class=nil},
    ["Jindo the Hexxer"] = {prio=4, marks={8}, type="KILL", class=nil},
    ["Gahzranka"] = {prio=1, marks={8}, type="KILL", class=nil},
    ["Zealot Lor'Khan"] = {prio=1, marks={6}, type="KILL", class=nil},
    ["Zealot Zath"] = {prio=1, marks={5}, type="KILL", class=nil},
    ["Zulian Tiger"] = {prio=4, marks={8}, type="KILL", class=nil},
    ["Razzashi Venombrood"] = {prio=3, marks={8}, type="KILL", class=nil},
    ["Hakkari Priest"] = {prio=2, marks={8}, type="KILL", class=nil},
    ["Hakkari Blood Priest"] = {prio=4, marks={8}, type="KILL", class=nil},
    ["Hakkari Witch Doctor"] = {prio=2, marks={8}, type="KILL", class=nil},
    ["Hakkari Shadow Hunter"] = {prio=6, marks={8}, type="KILL", class=nil},
    ["Hakkari Shadowcaster"] = {prio=2, marks={8}, type="KILL", class=nil},
    ["Gurubashi Berserker"] = {prio=2, marks={8}, type="KILL", class=nil},
    ["Gurubashi Axe Thrower"] = {prio=3, marks={8}, type="KILL", class=nil},
    ["Gurubashi Bat Rider"] = {prio=3, marks={8}, type="KILL", class=nil},
    ["Gurubashi Blood Drinker"] = {prio=6, marks={8}, type="KILL", class=nil},
    ["Gurubashi Champion"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Gurubashi Headhunter"] = {prio=7, marks={8}, type="KILL", class=nil},
    ["Son of Hakkar"] = {prio=8, marks={4}, type="KILL", class=nil},
    ["Spawn of Marli"] = {prio=3, marks={8}, type="KILL", class=nil},
    ["Ohgan"] = {prio=5, marks={7}, type="KILL", class=nil},
    ["Zulian Prowler"] = {prio=9, marks={0}, type="KILL", class=nil},
    ["Zulian Panther"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Zulian Cub"] = {prio=9, marks={0}, type="KILL", class=nil},
    ["Zulian Crocolisk"] = {prio=6, marks={8}, type="KILL", class=nil},
    ["Razzashi Cobra"] = {prio=6, marks={8}, type="KILL", class=nil},
    ["Razzashi Raptor"] = {prio=6, marks={8}, type="KILL", class=nil},
    ["Razzashi Serpent"] = {prio=4, marks={8}, type="KILL", class=nil},
    ["Razzashi Adder"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Razzashi Skitterer"] = {prio=9, marks={0}, type="KILL", class=nil},
    ["Razzashi Broodwidow"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Bloodseeker Bat"] = {prio=9, marks={0}, type="KILL", class=nil},
    ["Hooktooth Frenzy"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Powerful Healing Ward"] = {prio=2, marks={8}, type="KILL", class=nil},
    ["Superior Healing Ward"] = {prio=1, marks={8}, type="KILL", class=nil},
    ["Shade of Jindo"] = {prio=1, marks={8}, type="KILL", class=nil},
    ["Voodoo Slave"] = {prio=1, marks={8}, type="KILL", class=nil},
    ["Mad Servant"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Sacrificed Troll"] = {prio=9, marks={0}, type="KILL", class=nil},
    ["Withered Mistress"] = {prio=3, marks={8}, type="KILL", class=nil},
    ["Atalai Mistress"] = {prio=4, marks={8}, type="KILL", class=nil},
    ["Sandfury Speaker"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Witherbark Speaker"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Vilebranch Speaker"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Soulflayer"] = {prio=1, marks={8}, type="KILL", class=nil},
}

-- DIRE MAUL
TankMarkDefaults["Dire Maul"] = {
    ["King Gordok"] = {prio=1, marks={8}, type="KILL", class=nil},
    ["Cho'Rush the Observer"] = {prio=1, marks={8}, type="KILL", class=nil},
    ["Guard Moldar"] = {prio=2, marks={8}, type="KILL", class=nil},
    ["Alzzin the Wildshaper"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Lethtendris"] = {prio=6, marks={8}, type="KILL", class=nil},
    ["Hydrospawn"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Zevrim Thornhoof"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Prince Tortheldrin"] = {prio=1, marks={8}, type="KILL", class=nil},
    ["Immolthar"] = {prio=1, marks={8}, type="KILL", class=nil},
    ["Tendris Warpwood"] = {prio=1, marks={8}, type="KILL", class=nil},
    ["Magister Kalendris"] = {prio=1, marks={8}, type="KILL", class=nil},
    ["Pusillin"] = {prio=4, marks={1, 8}, type="KILL", class=nil},
    ["Captain Kromcrush"] = {prio=9, marks={0}, type="KILL", class=nil},
    ["Stomper Kreeg"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Pimgib"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Guard Fengus"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Gordok Captain"] = {prio=3, marks={8}, type="KILL", class=nil},
    ["Gordok Mage-Lord"] = {prio=4, marks={8}, type="KILL", class=nil},
    ["Gordok Warlock"] = {prio=4, marks={8}, type="KILL", class=nil},
    ["Gordok Brute"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Gordok Reaver"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Gordok Mauler"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Warpwood Treant"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Warpwood Stomper"] = {prio=3, marks={8}, type="KILL", class=nil},
    ["Warpwood Guardian"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Warpwood Crusher"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Warpwood Tangler"] = {prio=4, marks={8}, type="KILL", class=nil},
    ["Wildspawn Satyr"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Wildspawn Rogue"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Wildspawn Betrayer"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Wildspawn Trickster"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Wildspawn Hellcaller"] = {prio=4, marks={8}, type="KILL", class=nil},
    ["Wildspawn Felsworn"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Wildspawn Shadowstalker"] = {prio=4, marks={8}, type="KILL", class=nil},
    ["Phase Lasher"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Fel Lash"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Death Lash"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Netherwalker"] = {prio=5, marks={8}, type="KILL", class=nil},
}

-- TOWER OF KARAZHAN
TankMarkDefaults["Tower of Karazhan"] = {
    ["Lord Blackwald II"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Moroes"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Brood Queen Araxxna"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Clawlord Howlfang"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Master Blacksmith Rolfen"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Grizikil"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Shadowbane Alpha"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Shadowbane Glutton"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Shadowbane Ragefang"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Shadowbane Ambusher"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Shadowbane Darkcaster"] = {prio=4, marks={8}, type="KILL", class=nil},
    ["Dark Rider Apprentice"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Dark Rider Champion"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Skitterweb Crawler"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Skitterweb Darkfang"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Skitterweb Leaper"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Skitterweb Venomfang"] = {prio=4, marks={8}, type="KILL", class=nil},
    ["Grellkin Primalist"] = {prio=4, marks={8}, type="KILL", class=nil},
    ["Grellkin Channeler"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Grellkin Shadow Weaver"] = {prio=3, marks={8}, type="KILL", class=nil},
    ["Phantom Guardsman"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Phantom Servant"] = {prio=3, marks={8}, type="KILL", class=nil},
    ["Phantom Cook"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Haunted Blacksmith"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Haunted Stable Tender"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Shattercage Spearman"] = {prio=5, marks={8}, type="KILL", class=nil},
    ["Shattercage Magiskull"] = {prio=5, marks={8}, type="KILL", class=nil},
}