-- DecideMark decision tree: the non-governor paths -- combat gate, primary-mark
-- selection, free-icon fallback, and the early bails. The skull governor and CC
-- resolution live in governor_spec.lua (they exercise the board's skull ports).
local function decide(mob, mode, board)
    return TankMark:DecideMark(mob, "guid-1", mode or "SCANNER", board or make_board{})
end

describe("DecideMark combat gate (SCANNER)", function()
    it("skips when neither player nor mob is in combat", function()
        local i = decide({marks={4}, prio=5, name="M"}, "SCANNER", make_board{ playerInCombat=false, guidInCombat=false })
        eq_intent(i, nil, "not-in-combat")
    end)
    it("proceeds when only the mob is in combat", function()
        local i = decide({marks={4}, prio=5, name="M"}, "SCANNER", make_board{ playerInCombat=false, guidInCombat=true })
        eq(i.reason, "known", "reason")
    end)
    it("proceeds when only the player is in combat", function()
        local i = decide({marks={4}, prio=5, name="M"}, "SCANNER", make_board{ playerInCombat=true, guidInCombat=false })
        eq(i.reason, "known", "reason")
    end)
    it("does NOT gate in FORCE mode (batch path -- no combat check)", function()
        local i = decide({marks={4}, prio=5, name="M"}, "FORCE", make_board{ playerInCombat=false, guidInCombat=false })
        eq(i.reason, "known", "reason")
    end)
end)

describe("DecideKnownMark selection", function()
    it("takes a free non-skull primary mark", function()
        eq_intent(decide({marks={4}, prio=5, name="M"}), 4, "known")
    end)
    it("reports override=false on a clean (non-theft) take", function()
        eq(decide({marks={4}, prio=5, name="M"}).override, false, "override")
    end)
    it("falls back to the free tank icon when the primary is busy", function()
        local i = decide({marks={4}, prio=5, name="M"}, "SCANNER", make_board{ busy={[4]=true}, free=2 })
        eq_intent(i, 2, "known")
    end)
    it("yields no-icon when the primary is busy and nothing is free", function()
        local i = decide({marks={4}, prio=5, name="M"}, "SCANNER", make_board{ busy={[4]=true} })
        eq_intent(i, nil, "no-icon")
    end)
    it("skips a disabled primary and falls back to a free icon", function()
        local i = decide({marks={4}, prio=5, name="M"}, "SCANNER", make_board{ disabled={[4]=true}, free=2 })
        eq_intent(i, 2, "known")
    end)
    it("honors a disabled primary under FORCE (disabled ignored)", function()
        local i = decide({marks={4}, prio=5, name="M"}, "FORCE", make_board{ disabled={[4]=true} })
        eq_intent(i, 4, "known")
    end)
    it("bails on a sequential (marks>1) mob -- Batch owns that cursor", function()
        eq_intent(decide({marks={8,6}, prio=5, name="M"}), nil, "sequential-marks")
    end)
    it("bails on an explicit no-mark (marks[1]==0)", function()
        eq_intent(decide({marks={0}, prio=5, name="M"}), nil, "mark-zero")
    end)
end)

describe("DecideUnknownMark (mobData == nil)", function()
    it("takes the free tank icon", function()
        eq_intent(decide(nil, "SCANNER", make_board{ free=3 }), 3, "unknown-free")
    end)
    it("yields no-free-icon when nothing is free", function()
        eq_intent(decide(nil, "SCANNER", make_board{}), nil, "no-free-icon")
    end)
    it("respects the combat gate", function()
        eq_intent(decide(nil, "SCANNER", make_board{ playerInCombat=false, guidInCombat=false }), nil, "not-in-combat")
    end)
end)
